### ISSUE TITLE
We need a dedicated panel font color control alongside the panel background color controls

### ISSUE THREAD

**Issue by dikonov** [mate-desktop/mate-panel#102]
The MATE panel has the option of changing the panel background, including making it transparent and setting a custom color/texture. However, the font color of all the text drawn over the changed custom background is still controlled by the system-wide theme. 

The result is that the user cannot set a dark panel background color (or enable transparency with a dark desktop wallpaper) if the regular windows are light and the font color is black. The text becomes unreadable black on black and there is no control to invert the font color or set a custom one just for the panel.  In particular, it is impossible to mimic the Gnome3 default black panel - light windows colors. 

Please, add the setting to change the font color for the panel when the background color is changed or transparency is enabled
![panel_font_color_bug](https://f.cloud.github.com/assets/4271322/433977/d4c14d2a-af09-11e2-86c8-afa7fb5f07e7.jpg)
.

**Comment by jawz101** [comment]
That is not a smart answer and this shouldn't be closed.

It makes no sense to set them with a theme if panels let you set the background color.
If I have the ability to set the background color of my panel to be black independent of a theme, the font is immediately illegible.

**Comment by lukefromdc** [comment]
Cinnamon and gnome-shell split out panel theming entirely into separate themes-but they are still theme files that most end users cannot write, only download. MATE has more panel themablity in GTK3 than earlier MATE or GNOME 2 had in GTK2 in that the GTK theme can be different for the panel now. 

Such themes are can be dropped into your home directory as or added to  ~/.config/gtk-3.0/gtk.css with the .mate-panel-menu-bar selector separating them from the rest of the GTK theme. Alternately they can be included in GTK themes. That's exactly as much themability as Cinnamon offers except that nobody is packaging and offering 3ed party themes. The capability exists because I use it myself in  https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy .

You can use the "panel.css" files (match your GTK version) from that as a guide to writing your own custom theme for the panel.  Mate-panel from current git master supports background  images, gradients, colors, and  alpha(transparency). Vertical and horizontal panels can be separated for rotating images. The same css file stylkes text color, fonts (differ between GTK 3.22 and GTK 3.20 and earlier-see calendar-adjustment.css in gtk-3.22), menu popup styling, the whole works. Start with mine for the code, then set everything to your liking.
