### ISSUE TITLE
Is there a way to make the calander from the clock pop out into the center rather then left or right?

### ISSUE THREAD

**Issue by CuriousxOctopus** [mate-desktop/mate-panel#1269]
Is there a way to make the calander from the clock pop out into the center rather then left or right?
I have my clock centered in the middle of my panel, so it looks a bit weird. I don't mind editing the necessary files myself. I just don't know where to look.

Thank you

**Comment by lukefromdc** [comment]
Does this mean you now have the calendar NOT popping up over the applet (clock button) itself but instead elsewhere on the panel?

Also, do you have the panel containing the clock applet top, bottom, left, or right.

If you mean having the calendar centered on tje entire screen (both vertically and horizontally) that is not possible. If you are getting the calendar elsewhere than over the applet that's a bug.

Final note: if you are running mate-panel in a wayland session and not xorg, while that is now supported it is still a bit buggy.

**Comment by CuriousxOctopus** [comment]
I am sorry. I should have been more specific. When you click on then clock applet the calendar pics a corner of the clock applet and pops up. Rather then picking a corner I was wondering if I could edit it to make open from the center of the applet...
petty issue I know.

![Screenshot at 2021-11-11 07-52-48](https://user-images.githubusercontent.com/90221578/141207006-ef6334f6-5282-4afc-9724-5b9a307bd73e.png)

**Comment by CuriousxOctopus** [comment]
Oh wow I didn't realize it went that deep. I appreciate your time

**Comment by muktupavels** [comment]
Calendar popup is not menu...

https://github.com/mate-desktop/mate-panel/blob/master/applets/clock/clock.c#L874-L977

**Comment by lukefromdc** [comment]
Ahh yes, I was thinking of how menus are popped up. Still would be new compiled code to create user control options for where it appears, there are no installed files in mate-panel that can be edited to change this.

Thanks for catching that: this applet has the calendar popup and the right-click menu and the issue looked just enough like menu popup locations to pull me down the wrong path

**Comment by lukefromdc** [comment]
In fact, this WOULD be our code since the calendar is a custom widget. We'd need a new gsettings preference to store the default and user choices, code to both set and read it, and 3 options in the code to pop up the calendar, selected by the results of reading that preference. All of this would be in the compiled code except the new gsettings preference in the schema-and THAT gets compiled in the local machine when the package is installed though that job is easily retriggered for all schemas. Away frim my desktop right now.

Anyway, we don't have that preference now in the compiled code, so no way to change this on the current binaries.

On 11/13/2021 at 2:02 PM, ***@***.*** wrote:
>
>Ahh yes, I was thinking of how menus are popped up. Still would be 
>new compiled code to create user control options for where it 
>appears, there are no installed files in mate-panel that can be 
>edited to change this.
>
>Thanks for catching that: this applet has the calendar popup and 
>the right-click menu and the issue looked just enough like menu 
>popup locations to pull me down the wrong path
>
>On 11/13/2021 at 8:53 AM, "Alberts Muktupāvels"
