### ISSUE TITLE
Window List applet is not working on Wayland

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-panel#1294]
#### Expected behaviour

Running mate-panel on Wayland (in particular Labwc and Sway) with list of all running applications on the panel.

#### Actual behaviour

Tasklist is not working, and I can't add tasklist applet to the panel

#### Steps to reproduce the behaviour

Run mate-panel on any Wlroots-based compositor (I use Labwc and Sway), and add tasklist applet to the panel

#### MATE general version

1.26

#### Package version

1.26.2

#### Linux Distribution

Ubuntu 22.04 LTS (daily builds)

**Comment by lukefromdc** [comment]
For an applet to run in Wayland it has to built in-process. Out of process applets used xembed/GtkPlug/GtkSocket and those are not usable under wayland.

The clock, fish, wncklet (includes window list), and notification area can be built either in process or out of process, and out of process is still the defaulr.

**Comment by Sunderland93** [comment]
I see... If I build mate-panel with in-process - could it break something?

**Comment by Sunderland93** [comment]
So why not build with in-process by default?

**Comment by lukefromdc** [comment]
Really this is a distro-level decision to build in-process or out, and the default has not been changed probably since GNOME 2's early days. Note that a crashing in-process applet takes down the whole panel, a crashing out of process applet does not. Historically crashy applets have been common enough to make out of process a real advantage for many users.

At the moment,all or most of the applets in the mate-applets package are out of process-only, and to fully support wayland all of these would have to be ported over to be buildable in-process.

On 2/18/2022 at 6:22 PM, "Aleksey Samoilov" ***@***.***> wrote:
>
>So why not build with in-process by default?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mate-desktop/mate-
>panel/issues/1294#issuecomment-1044963418
>You are receiving this because you commented.
>
>Message ID: <mate-desktop/mate-
***@***.***>

**Comment by raveit65** [comment]
Ok, this is fixed now with latest conmmits in master. Applet runs fine now.
