### ISSUE TITLE
netspeed applet doesn't show any tning

### ISSUE THREAD

**Issue by alirezaimi** [mate-desktop/mate-panel#1325]
#### Expected behaviour
Show network transfer bit rates .

#### Actual behaviour
Doesn't show any changes. 

#### Steps to reproduce the behaviour
do not know ! just install new debian on my laptop with mate-desktop and add this applet and this happened. 

#### MATE general version
mate-desktop:
  Installed: 1.26.0-1

#### Package version
mate-applets:
  Installed: 1.26.1-1

#### Linux Distribution
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian

#### Link to bugreport of your Distribution (requirement)

    Aug 16 11:01:30 imi dbus-daemon[1037]: [session uid=1000 pid=1037] Activating service name='org.mate.panel.applet.NetspeedAppletFactory' requested by ':1.28' (uid=1000 pid=1176 comm="mate-panel")
    Aug 16 11:01:30 imi dbus-daemon[1037]: [session uid=1000 pid=1037] Successfully activated service 'org.mate.panel.applet.NetspeedAppletFactory'
    Aug 16 11:01:30 imi kernel: [41735.793061] ERROR @wl_dev_intvar_get : 
    Aug 16 11:01:30 imi kernel: [41735.793067] error (-1)
    Aug 16 11:01:30 imi kernel: [41735.793072] ERROR @wl_cfg80211_get_tx_power : 
    Aug 16 11:01:30 imi kernel: [41735.793073] error (-1)
    Aug 16 11:01:31 imi kernel: [41736.795113] ERROR @wl_dev_intvar_get : 
    Aug 16 11:01:31 imi kernel: [41736.795120] error (-1)
    Aug 16 11:01:31 imi kernel: [41736.795126] ERROR @wl_cfg80211_get_tx_power : 
    Aug 16 11:01:31 imi kernel: [41736.795128] error (-1)
    Aug 16 11:01:32 imi kernel: [41737.796585] ERROR @wl_dev_intvar_get : 
    Aug 16 11:01:32 imi kernel: [41737.796592] error (-1)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017429

**Comment by thesquash** [comment]
I looked at the Debian bug report you created, and I noticed this:

```
[...]
Kernel taint flags: TAINT_PROPRIETARY_MODULE, TAINT_WARN, TAINT_OOT_MODULE, TAINT_UNSIGNED_MODULE
[...]
```

That would indicate that some proprietary driver is running on your Debian system.  That by itself wouldn't be much of an issue; however, I notice that the log that you gave us in this issue report contains a number of `wl` (wireless network) errors -- coming from the kernel, the same thing that is marked as "tainted" due to the proprietary driver(s).

First of all, is it true that the network to which you're connected is a wireless network (not a wired network such as Ethernet)?

Second, find out what driver is being used to control the networking device.  You can do this by first finding the "interface name" of the network device -- right-click on the Netspeed Applet and choose **Device Details** from the menu; the title of the window that subsequently pops up should be **Device Details for *XXX***, where ***XXX*** is the interface name.  Now find out what driver it's using by running this terminal command (replacing `XXX` with the interface name):

```
dmesg | grep XXX
```

(If you get an error from that, you will have to run the command again as root.)  At least a few lines of output should be printed, some along the lines of:

```
[   25.927964] b44 ssb0:0 XXX: Broadcom 44xx/47xx 10/100 PCI ethernet driver 00:0b:db:2f:a6:a2
```

The `b44` part right after the square brackets at the left, is the driver name.  Now, run this command, replacing `YYY` with the driver name (in my case, `b44`):

```
dmesg | grep YYY
```

Then copy the output from that command, and paste it into a reply to this issue.

Thanks.

**Comment by raveit65** [comment]
No answer from reporter, closing.
