### ISSUE TITLE
Mate Panel Shadow

### ISSUE THREAD

**Issue by TaylanTatli** [mate-desktop/mate-panel#193]
Mate panel shadow not working on startup. But when i run "marco --replace" it's working.
##

**Comment by mrnhmath** [comment]
Is this still relevant with GTK3 release? Or can it be closed in #617 favour and vice-versa?

**Comment by otwesou** [comment]
@mrnhmath, #617 still applies for me with gtk3. as for this bug, running marco --replace didn't result in a shadow being added for me.

**Comment by Yupy** [comment]
Not working anymore with GTK3 thats why I ditched the MATE desktop I hate that flat look.

I've tried many many ways to make it appear even with compiz doesen't appear.

Ikey from Solus did a pull request: https://github.com/mate-desktop/mate-panel/pull/593 this might help?

**Comment by raveit65** [comment]
And there are open questions with this PR.......

**Comment by Dolsilwa** [comment]
Does anybody has any news on panel shadow in MATE?

**Comment by Yupy** [comment]
@Dolsilwa, I doubt they will ever put back the panel shadow, is a bad choice they removed it :( this made me stop using the MATE DE.

That flat look with some darker wallpapers you can barely see it when the themes have a darker color.

**Comment by raveit65** [comment]
Guys, do you really think we removed it on purpose ?
This is a fallout from switch to gtk+3.
If someone have an idea to fix it we'll include the fix shortly.
Fixes are welcome.....
But if this is a reason for to use another desktop, please do.
Sorry, we can't help you at the moment.

**Comment by Dolsilwa** [comment]
@Yupy You can add panel shadow in MATE through Compton, but it's not a perfect solution (when you maximize an app, panel shadow is drawn on window titlebar).

@raveit65 I know that it was not removed on purpose :-) I know that it's gtk3 transparency fault (or so i understand). And i was just curious, because year ago there were some ideas and some commits done to bring back panel shadow. Right now i'm adding artificial shadow directly to wallpaper (in Gimp), so it's not an issue that would make me stop using MATE :-) MATE is most vesatile GTK-based DE, and is my favourite. That being said, MATE lacks a bit in "looks" department. Right now, the best default look has Solus, partly because when panel is only at the bottom of desktop, you don't need panel shadow. But Ubuntu-MATE (which i use) looks a bit ugly with flat, shadow-less panel at the top of desktop. But with panel shadow, default Ubuntu-MATE just looks a lot better (Ubuntu-MATE 16.10 below).

![zrzut ekranu w 2018-04-15 17-12-16](https://user-images.githubusercontent.com/36594353/38779982-5c012e60-40d0-11e8-8eb8-ce22d5b2d7c5.png)

**Comment by Yupy** [comment]
I tought the panel shadow was removed because people are starting to adopt the flat look.

**Comment by raveit65** [comment]
With that commit https://github.com/mate-desktop/mate-panel/commit/c4aedbddc01da6c0bf439e4229d77ae4c137df45
An example css for Menta and other light themes which can be used in
~.config/gtk-3.0/gtk.css
```
.mate-panel-menu-bar.horizontal.top > grid {
    border-style: outset;
    border-width: 0px 0px 1px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.horizontal.bottom > grid {
    border-style: outset;
    border-width: 1px 0px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.left > grid {
    border-style: outset;
    border-width: 0px 1px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.right > grid {
    border-style: outset;
    border-width: 0px 0px 0px 1px;
    border-color: rgba(0, 0, 0, 0.23);
}
```

**Comment by lukefromdc** [comment]
A true shadow can't be rendered on the panel's window as the window does not extend beyond the panel (  _GTK_FRAME_EXTENT value zero or maybe not defined). This suggested workaround uses a border to simulate a shadow and should work. A fit fancier would be to screenshot a desired shadow on some other window, and in GIMP or a similar program  cut out just the top, bottom, left, and right shadows and save samples of each as .png files. These could then be used to define an image border that would look exactly like a shadow because it is a screenshot of a shadow. That's how i copied theme elements between GTK2 and GTK3.

**Comment by raveit65** [comment]
Closing, not posts since years.
