### ISSUE TITLE
Desktop launchers drag-and-drop-copied to panel vanish silently when removed from desktop

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-panel#287]
doing this
1. Create some launcher on the desktop (RM->Create Launcher)
2. Copy launcher to some panel (Drag-And-Drop)
3. Remove launcher from desktop
4. Logout+Login (so mate-panel is refreshed)

silently leaves the user with no launcher visible any more in
the panel. It's still in the panel's config though; (for example)
resurrecting the Desktop Launcher from the Trash makes it visible
again after Logout/Login.

There is no way to notice for the user (i.e., via the MATE
desktop) that such a broken panel item ist still configured. The
only way to see is via the user's ".xsession-errors" file
("Unable to open desktop file"...).

Imho, one of the following simple solutions would fix this:
- Just show the broken items in the panel anyway, so the user can deal with them.
- Add a pop-up whether the user wants to remove the broken items (like for broken panel apps).

Furthermore, when Drag-and-drop the desktop launcher to the
panel, it shows a '+', which should read 'copy', but this
obviously is not a real copy -- a different issue (this is about
error handling only), but related.

Reported via Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771676
##

**Comment by monsta** [comment]
Confirmed in 1.10.

- it's enough to ```killall mate-panel``` instead of logout/login
- if you re-create the same launcher on desktop (instead of restoring it from trash) and then restart the panel, the effect will be the same - the launcher reappears on the panel.

And I really can't see the difference between copying and moving (with Shift held) the launcher here: both actions will do the same. "Moving" won't remove the launcher from desktop. It seems more like a "symlink" behaviour to me...

**Comment by infirit** [comment]
It is actually intended behaviour. What it does is create a ``new`` launcher for the launcher (desktop file) on your desktop. It may not be obvious but this is how it works.
