### ISSUE TITLE
Increase distance between icons in panel

### ISSUE THREAD

**Issue by alexkieling** [mate-desktop/mate-panel#465]
The icons of applications added to the panel are placed very close to each other. It would look a lot better if they had a little margin on both sides.
##

**Comment by kn00tcn** [comment]
you also want to use the separator elsewhere & not have that get really thin, right?

maybe i will try adding a feature that lets you control the width of launcher items

(of course, a much better way would be a new applet that lets you choose quick launch icons in bulk, rearrange them, & set padding... also it seems like the gtk theme controls notification icon padding, so maybe launcher icons can use this same amount)

**Comment by alexkieling** [comment]
I'm not sure the distance between the quick launch icons needs to be configurable. Using the same width as the notification icons seems good enough.

**Comment by lukefromdc** [comment]
Individual application launcher icons can easily be respaced, I've always moved them to a spacing that suits my eye well back into the GNOME 2 days.

**Comment by kn00tcn** [comment]
are you saying you manually move them one by one? that's just... wrong

the purpose of computed padding is so that every single space is identical & can be changed all at once no matter if it's 1 or 100 icons (even better to match the gtk theme's padding that is applied to the notification icons)

i'm thinking about how to properly do this, most likely a new applet will be made where you choose the icons/launchers & reorder them in a settings screen, this way the old individual icons will not break for anyone (especially if they have ungrouped needs like putting them in specific spots across the entirety of the panel)

**Comment by lukefromdc** [comment]
That's what I've ALWAYS done, all the way back to 2007 or so.

**Comment by lukefromdc** [comment]
Keep in mind, getting the launcher icons exactly where you want them when you first drag them into the panel is not easy, thus the need to respace them afterwards.

**Comment by alexkieling** [comment]
Creating a new applet sounds like the safest option. In that case, it might be a good idea to review quick launcher applets from other desktop environments and borrow the best features.

**Comment by kn00tcn** [comment]
that's my point, it's not supposed to be hard, i'm not saying you're (luke) wrong, you're utilizing the only available feature, i'm saying the DE has a responsibility

just got another useful idea, an interface to move these things by numeric pixels (whatever the dconf position value is), so it's the same result as using the mouse, but with some - + buttons so the user doesnt need to be a pro gamer to make precise adjustments

related would be a way to load/save preset panels (might help those multi resolution people that have problems with right side items), i think ubuntu mate or mint have this, not sure why their usability settings dont end up upstream here

**Comment by pepa65** [comment]
On the 1.18 release, the spacing was increased, and now my icons don't fit anymore. Is there a way to decrease spacing?

**Comment by kn00tcn** [comment]
(i havent checked yet) are you sure it wasnt the gtk theme that increased spacing? can you rearrange them or doing that results in the total width of the icon set being wider than before?

**Comment by pepa65** [comment]
I've had to downgrade, because my start menu icon on the left was obsured by 4 other icons bunched on top of it (so the total width of each icon space --the padding-- increased). The general problem with mate-panel is, there is no way to access the panel settings, otherwise I could have made the panel (and thereby the icons) narrower.

I don't know whether it was the theme or what, but it would be good to have a general way to adjust spacing parameters.

**Comment by kn00tcn** [comment]
individual icons you need to unlock, then drag them around until they fit into place again, then relock them, unfortunately not as nice as xfce where you have a sorted list that always auto fits to make it easier

**Comment by pepa65** [comment]
I actually opened #614 - I'm on Ubuntu 16.04 and yesterday added ppa:jonathonf/mate-1.18

**Comment by pepa65** [comment]
I am not able to arrange them as before, because the number of icons I had no longer fit in the width of the panel (which is at 100%).

**Comment by ajeetdsouza** [comment]
I suppose you could take a cue from Xfce's separator applet for this. They also have a small app to organise panel items.

**Comment by lukefromdc** [comment]
I do NOT want my launchers forcibly separated by their own width, and in fact would have to locally revert any such hardcode. I have one panel only, with the window list and a lot of launchers on the same panel. Thus I cannot use a panel with hardcoded miniumum launcher separation on the order of their own width.
