### ISSUE TITLE
request some look'n'feel improvement

### ISSUE THREAD

**Issue by r105m** [mate-desktop/mate-panel#493]
I think every mate theme, provided with my distro (fedora) is ugly and looking as not completed crap. 
The only more or less good looking theme is adwaita/clearlooks.
I think Adwaita must be supported as well and setted by default.

But in adwaita some widgets is looking ugly after switching to gtk3. Please, take a look for screenshot:
https://postimg.org/image/xs3z6cm6b/

1. buttons in panel is looking ugly without a margin. 
2. Is these elements is a really buttons? or these marked elements can look like underlined blue text, like in application menu?

So, what you can do to improve user expirience:
1. Exclude crappy gtk themes from standart packages: menta, submarine, ets. all of these themes is poor and discussing.
2. Make full support for adwaita

**Comment by raveit65** [comment]
file out a report against adwaita theme.

**Comment by r105m** [comment]
and what is that means?

**Comment by lukefromdc** [comment]
We have no control over Adwaita, that's GNOME's baby. Theme tastes are very personal, that's why we offer so many. We did extra work in the GTK 3 port to ensure that Adwaita would work, at first we got things like a totally transparent panel.  Anyway, every theme has its fans, as proven by the fact that every theme gets issues reported against it for correction. 

Your screenshot shows things we really have no control over short of hardcoding things into the panel that would break all other themes. You could use GtkInspector and/or our own themes as templates to write a gtk.css file containing only these elements as you like them to drop into your .config/gtk-3.0 directory. The selectors to use for the margins you want on panel buttons will be 
#tasklist-button and #tasklist-button:checked or for every button on the panel
 .mate-panel-menu-bar button assuming you are using GTK 3.20 or 3.22

**Comment by lukefromdc** [comment]
We have no control over Adwaita-and themes are a personal taste. Lots
of people do prefer our themes to Adwaita, myself included.
