### ISSUE TITLE
mate-panel 1.17.0: crash applets using --with-in-process-applets

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-panel#499]
I tried to build mate-panel 1.17.0 using --with-in-process-applets=all parameter.
All went fine, until i tried to add and remove the applet from the panel.
It crashed the panel and respawn.

When i removed the parameter, all the applets are working fine. They gets added and removed normally.

I wonder if this parameter no longer works?

Slackware current with GTK+3 3.18.9

cc @lukefromdc

**Comment by lukefromdc** [comment]
Until recently removing an applet would ALWAYS crash the panel with GTK3, but when it respawned the removed applet would be gone. I have not seen crashes on adding applets anytime I can remember.

BTW, with GTK 3.22, in-process applets cause all kinds of panel rendering bugs with things not being redrawn due to changes in GTK itself.  
https://github.com/mate-desktop/mate-panel/issues/468
Until someone finds a fix for that (it is a draw on native window issue it seems), in-process applets won't be usable anyway once all distros are shipping GTK 3.22/

**Comment by willysr** [comment]
I tried to remove a fish applet from panel and it worked fine with 1.17.0 without --with-in-process-applets=all parameter. No crashes here.

So i will leave this bug report open until every distro ship GTK 3.22 then.

**Comment by lukefromdc** [comment]
It's a bug so yes this should stay open until either someone finds a fix or no GTK version in which it exists is still in use

**Comment by monsta** [comment]
> Until recently removing an applet would ALWAYS crash the panel with GTK3, but when it respawned the removed applet would be gone. I have not seen crashes on adding applets anytime I can remember.

Do you mean https://github.com/mate-desktop/mate-panel/issues/447?

**Comment by lukefromdc** [comment]
Yeah, its https://github.com/mate-desktop/mate-panel/issues/447

**Comment by monsta** [comment]
This is probably fixed by https://github.com/mate-desktop/mate-panel/pull/622.

**Comment by raveit65** [comment]
Why not closing it instead of creating an unwanted email-notification-spam in my mail box? 😃

**Comment by monsta** [comment]
Well I didn't know for sure
