### ISSUE TITLE
Mate panel shows wrong window previews when using compiz and multiple workspaces

### ISSUE THREAD

**Issue by boden** [mate-desktop/mate-panel#545]
When working with several workspaces and compiz, the thumbnail previews of program windows that appear when the mouse hovers over the panel show the wrong programs. For instance, the first (left) program on workspace one shows the preview of the first (left) program on workspace two. When switching to marco, no previews seem to be shown.

System: Ubuntu Mate 16.04.02, kernel 4.8..0-41, mate-panel 1.16.1, compiz 1:0.9.12.2+16.04.20160823-0ubuntu1, skylake processor with integrated intel graphics

**Comment by lukefromdc** [comment]
Compiz itself handles draws thumbnail previews when hovering over the panel buttons for a window, I assume you are talking about these? I just tested them, they are correct in my setup, but I am using a hacked compiz (for another bug) in Debian Unstable. This might be a bug in your version of compiz rather than in mate-panel at all.

**Comment by boden** [comment]
That sounds like a reasonable explanation. Sorry for reporting to the wrong project then. Sometimes hard to guess at the source of an issue without knowing so much about the internals. Thanks for clarifying!

**Comment by monsta** [comment]
Well, it's better to report it to compiz developers then.
