### ISSUE TITLE
[Feature request] Option to disable status notifiers in notification area applet .

### ISSUE THREAD

**Issue by IKRadulov** [mate-desktop/mate-panel#547]
Something like a gsetting should work . I am asking for this since there are other applets that implement status notifiers thus making duplicate notifiers like this : 
![2017-03-30 12-10-16](https://cloud.githubusercontent.com/assets/21968311/24496789/e236854a-1541-11e7-8dc5-27e01ea201ed.png)

**Comment by rilian-la-te** [comment]
If you does not like my SNTray, just don't use it:) And what are other applets?

**Comment by IKRadulov** [comment]
You got me wrong here . I have a vala-panel compiz reloaded setup and I like it . the thing is that Mate notification area now has status notifier supports and the indicators duplicate . That is why I am asking for a option to dissable status notifiers in the notification applet of mate , So I can use your applet withought the duplication of indicators. The others are your applet and snw-plugin.

**Comment by muktupavels** [comment]
@rilian-la-te ubuntu? there is indicator-applet for this and it does not show x11 try icons. to get these icons user most likely adds notification-area applet that handles both things...

For gnome-panel I created new applet (far from ready, but...), but mate-panel merged with notification-area. So setting to disable it makes sense.

**Comment by rilian-la-te** [comment]
I have a https://github.com/rilian-la-te/xfce4-sntray-plugin. Despite of name, it is very configurable applet for all GTK3 desktops. But StatusNotifier only (and I will never implement XEmbed, I think XEmbed must die).
Indicator-applet not configurable as my. And I also vote for ability to disable StatusNotifier in mate na-tray. Or I must port XEmbed to mate-panel again. But vala-panel XEmbed has many issues, because it is just copy from old LXPanel.

**Comment by monsta** [comment]
The duplicate icons problem had been fixed recently: https://github.com/mate-desktop/mate-panel/issues/539, https://github.com/mate-desktop/mate-panel/pull/543

**Comment by IKRadulov** [comment]
Nope . Compiled mate-panel from git on Manjaro Linux and still the same .
![2017-04-04 01-12-37](https://cloud.githubusercontent.com/assets/21968311/24633917/d6981c7c-18d3-11e7-9e63-85bff9b758f1.png)

![2017-04-04 01-13-26](https://cloud.githubusercontent.com/assets/21968311/24633953/fb33dd00-18d3-11e7-9122-2f53bade10a7.png)

**Comment by monsta** [comment]
Ok, I see, it's not the same problem then.

@cwendling: what do you think about this request?

**Comment by cwendling** [comment]
Well… I'd first ask why use an extra applet now the notification area handles SNI.  Apart from that, I don't know, but I guess that if there's a reasonable use case not to have SNI in notification area why not have a setting.  It'd shouldn't be too hard to implement, although not very fun.

**Comment by IKRadulov** [comment]
Couse the applet by rilian-la-te  is very configurable + there is another one called snw-plugin. I personaly don't like having a mash up of status notifiers and xembeded in one place since there is no big diffirence on how they look, and it's really confusing when you don't know if the program is compiled with status notifiers support and you try to left click and nothing happens .

**Comment by monsta** [comment]
So the requested gsettings key had been added via https://github.com/mate-desktop/mate-panel/pull/600. It's available starting from 1.18.5.

```
$ gsettings get org.mate.panel enable-sni-support
false
```

**Comment by monsta** [comment]
Well... after seeing lots of problems with SNI support, I started to think it was a bad decision to make it a part of tray area applet instead of creating a separate applet (like it had been originally done in gnome-panel).

For the record - I guess not everyone knows it - the reason for adding SNI support was the breakage of keyboard navigation in the tray area when any Qt 4 app was showing its tray icon: https://github.com/mate-desktop/mate-panel/issues/506.

**Comment by alexarnaud** [comment]
Le 22/01/2018 à 15:31, monsta a écrit :
> For the record - I guess not everyone knows it - the reason for adding 
> SNI support was the breakage of keyboard navigation in the tray area 

The issue It's more than just the breakage of keyboard navigation in the 
notification area. Without the keyboard navigation most of people in the 
blind and visual-impaired community would stay on Windows or Mac because 
"Linux doesn't work".

> when any Qt 4 app was showing its tray icon: #506 
> <https://github.com/mate-desktop/mate-panel/issues/506>.

FYI, It's also the case with Qt 5 apps.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by lukefromdc** [comment]
A lot of the SNI bugs are being fixed, one after another

**Comment by alexarnaud** [comment]
Le 22/01/2018 à 20:19, lukefromdc a écrit :
> A lot of the SNI bugs are being fixed, one after another

Right, thanks for your hard work on this area.

Le 22/01/2018 à 19:21, monsta a écrit :
> How do you think, would a separate applet (ours or third-party one) solve the a11y problem too?

It could be OK, we used that solution on Mate 1.8 but I don't think we 
should do that.

IMO, The goal we should have to be make it possible to have SNI support 
enabled by default on all distributions. If SNI support was not enabled 
by default we've not seen most of the bugs.
Make keyboard navigation and accessibility feature outside of the main 
tree makes those features not developed and maintained.

Information technologies are one of the way the visual-impaired could be 
empowered and if we expect to have the free software a freedom for this 
population we need to include them.
Keyboard shortcuts navigation could be also useful for people that like 
it and to those with reduced mobility.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment]
> It could be OK, we used that solution on Mate 1.8 but I don't think we should do that.

Interesting, which applet was it at that time?

**Comment by alexarnaud** [comment]
Le 30/01/2018 à 13:51, monsta a écrit :
>     It could be OK, we used that solution on Mate 1.8 but I don't think
>     we should do that.
> 
> Interesting, which applet was it at that time?

It's the GNOME Panel implementation adapted for Mate 1.8 by Hypra. It's 
downloadable at http://git.hypra.fr/alexarnaud/mate-status-notifier-applet

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"
