### ISSUE TITLE
Unable to change number of workspaces in workplace switcher

### ISSUE THREAD

**Issue by DavidGriffith** [mate-desktop/mate-panel#548]
After a right-click->Preferences selection on the Workplace Switcher, I see that the options to change the number of workspaces and workspace names have been greyed out and are not usable.

**Comment by lukefromdc** [comment]
What window manager are you using? I have not had that issue at all. In Marco changing the number of workspaces works fine on Debian Unstable with all of mate from git master.  Even in compiz where wrong values are shown and only compiz itself (via ccsm) can change the number of workspaces, the gui is not grayed out, the input is just ignored. Probably should be grayed out in compiz however.

**Comment by DavidGriffith** [comment]
I'm using Marco.

**Comment by lukefromdc** [comment]
Which version of mate-panel and of marco are you using, and if they are 1.16 or earlier are they built with GTK3 or GTK2? Also what distro?

**Comment by DavidGriffith** [comment]
I'm using Debian 9 (Stretch).  Marco 1.16.0.  Mate-panel 1.16.0.  Using GTK3 version 3.22.9-4.  All this was installed from the Debian repos.

**Comment by lukefromdc** [comment]
I literally never tried to do this until this report was filed, but with GTK 3.22.10 or 3.22.11, mate-panel 1.18 and marco 1.18 (compiled locally) on Debian Unstable I cannot duplicate this, so it may have gotten fixed somewhere between 1.16 and 1.18. Can anyone else test this?

**Comment by DavidGriffith** [comment]
That reminds me of of something.  I've been asking around how I can cause a locally-compiled Mate component to be used instead of the one that comes in the Debian repo.  I haven't received a workable answer and it reads like you've managed to do this easily and sensibly.

**Comment by lukefromdc** [comment]
Uninstall the Debian packages (usualy several per mate application), make install the local version is what you will need to do. To revert use make uninstall to remove the local package, then reinstall the relevant .debs.

I don't have Debian's distributed packages installed at all, only my own for anything in MATE.  Simplest way to do that is purge all of MATE from Debian and make install the packages from source, following the build order that starts with mate-common. I think they will work in /usr/local if installed this way, but if not they all have make uninstall targets that can be used for removal as well.

I  take the extra trouble to pack my built programs into Debian packages with checkinstall, one debian package to one source package which is fewer packages then Debian's split-up foo, foo-dev, foo-data etc packages. In so doing I have to deal with a checkinstall bug that picks up icon cache files, gschemas.compiled, and extras in /usr/share/mime by manually repacking from the temporary directory checkinstall makes. A bit complex but I've done this since 2015 so I'm used to it.

My own system is a hybrid really of Debian Unstable with a lot of custom work. All of MATE, all of compiz, GTK3 and libglib, the kernel and anything else that touches disk encryption, full custom theming, and more.

**Comment by DavidGriffith** [comment]
I think the problem has something to do with my attempt to try out bleeding-edge Mate components.  I created a guest user, who had the same problems.  But when I made a fresh install of Stretch, the problem did not appear.

**Comment by phocean** [comment]
Same here, I have to do the configuration with dconf.
I am not bleeding edge in any way, just using Ubuntu Mate 18.04 and it also happen with a new user (fresh profile).

**Comment by BrentBradburn** [comment]
As described, the GUI for this seems to be broken for Ubuntu Mate 18.04.

Here's how to use the command-line to set the number of workspaces:
`gsettings set org.mate.Marco.general num-workspaces 30 ## replace '30'
`
Further description here: https://askubuntu.com/questions/1142245/ubuntu-mate-18-workspace-configuration-file

**Comment by linas** [comment]
FWIW, Still have this problem, Debian Stable (bookworm) January 2025. Problem showed up a year ago, I hoped it would "fix itself", but .. heh. No such luck.
