### ISSUE TITLE
Custom Application Launcher uses xterm instead of mate-terminal

### ISSUE THREAD

**Issue by oliver-joos** [mate-desktop/mate-panel#57]
I use the new Mint 14 with mate-panel 1.4.0. If I add a "Custom Application Launcher" to a panel with type "Application in Terminal" then it does not work. Clicking the launcher shows an error dialog saying "Failed to execute child process "xterm" (No such file or directory)".

I found a forum thread about this problem:
http://forums.linuxmint.com/viewtopic.php?f=206&t=113734

Their workaround is to choose type "Application" and prepend the original command like this:
  mate-terminal -e 'original_command'

One post in the forum thread advises to create a symbolic link in /usr/bin/ named "xterm" to "mate-terminal". This did not work for me nor was it necessary.
##

**Comment by MarioMey** [comment]
I just made a clean instalation of Ubuntu Mate 14.04 (from http://ubuntu-mate.org/) and this bug is still here. So, I think it's not only a Mint bug.

I tried:

sudo ln -s mate-terminal xterm ----> Doesn't work.

sudo ln -s /usr/bin/mate-terminal /usr/bin/xterm && sudo chmod +x /usr/bin/xterm ---> The error message isn't shown... but the app doesn't launch (I don't know why)

In *Custom Application Launchers*, there is Mate Terminal.

By doing "export TERM=mate-terminal", it doesn't fix anything.

Any news...?

**Comment by kacernator** [comment]
This bug still exists in Linux Mint 17.2 Mate.

**Comment by MoonSweep** [comment]
So, to summarize:

Contrary to what was said at the beginning of this thread, this is not a Mint-only issue, and this has nothing to do with the TERM variable. This is a known bug from GLib which has a hard-coded set of terminals to try and launch, and several of them are missing from this list (not only mate-terminal, but xfce-terminal or konsole for example are also missing).

Knowing how the Gnome guys are oblivious to anything outside of Gnome, I think it's no use to ask them to fix this issue in GLib, that's why so I made a patch handling mate-terminal and posted it in the Debian BTS, then when mate-terminal packages started to provide a wrapper compatible with xterm, I updated the patch to handle x-terminal-emulator (which is a Debian alternative for all terminal emulators compatible with xterm), thus allowing GLib in Debian (and derivatives) to handle not only mate-terminal but all terminals which can be set as this alternative.

Now we have to wait for the patch to be included in the Debian package, which will automatically fix the bug in the next versions of Ubuntu and Mint as well. I'll ping the Debian bug right now.

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773915
Ubuntu bug: https://bugs.launchpad.net/linuxmint/+bug/1238964

**Comment by infirit** [comment]
https://github.com/mate-desktop/mate-desktop/issues/121#issuecomment-63468635

>I tracked it down to panel_app_info_launch_uris in https://github.com/mate-desktop/mate-panel/blob/master/mate-panel/libpanel-util/panel-launch.c#L97

re-opening this one even-though this is a glib problem.

**Comment by charisz** [comment]
debian jessie / MATE Desktop Environment 1.8.1

If a try open a text file from the context menu (right click) and I choose vim,
it is opened with xterm instead of mate-terminal.
*Is this related with this issue?*

- the `vim.desktop` contains exec=vim %F
- `echo $TERM` shows xterm-256color
- x-terminal-emulators opens mate-terminal
- `update-alternatives --config x-terminal` emulator is set to `/usr/bin/mate-terminal.wrapper`

**Comment by raveit65** [comment]
Why using a desktop file for Vim?
I can use Vim without any problems inside mate-terminal here in fedora.
And if the you vim version with desktop file use xterm than please file out a report against vim.

**Comment by charisz** [comment]
I don't use the desktop file, it's created by the system. I'd try to find out why vim opened from caja's context menu starts with xterm instead of mate-terminal. I googled a lot and found this is issue as the only one clue for this. Because it shows some similarity.

**Comment by raveit65** [comment]
> I'd try to find out why vim opened from caja's context menu starts with xterm instead of mate-terminal

I don't have any entry in context-menu about vim, because i don't have a desktop file for vim ;)
Maybe you find a hint in this desktop file.

**Comment by charisz** [comment]
No. It's wrong direction. There is nothing.
```
[Desktop Entry]
Name=Vim
GenericName=Text Editor
GenericName[de]=Texteditor
Comment=Edit text files
--- languages ---
[Desktop Entry]
Name=Vim
GenericName=Text Editor
GenericName[de]=Texteditor
Comment=Edit text files
```

**Comment by MoonSweep** [comment]
@charisz This is *precisely* the same problem, [read my previous comment](https://github.com/mate-desktop/mate-panel/issues/57#issuecomment-127224654) for a summary of the situation. It's a GLib bug, and it's obvious that neither the Gnome developers (upstream for GLib) nor the Debian Gnome maintainers (who have several members in common, which I didn't know at the time I wrote my previous comment) are not in a hurry to fix it ([see how the Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773915) I filled turned out).

@raveit65 The desktop file is part of vim's source tarball. If what you say is true, then Fedora probably doesn't ship it in their binary package; Debian (and its derivatives) do.

**Comment by raveit65** [comment]
Thanks for clarification.
Indeed, normal vim package does not ship a desktop file in fedora, only vim-x11 gui package ships one.
But honestly does vim need a desktop file for working ;)

**Comment by charisz** [comment]
@MoonSweep Thank you, I calmed down, and am waiting patiently for some soultion.
@raveit65 For me vim is the text editor for everything, and if I use graphical file manager (such as caja), I'd open files with vim as well; the desktop files support this.

**Comment by git-oliver** [comment]
Unfortunately this issue still exists in MATE 1.14 of Linux Mint 18.0

@MoonSweep: thanks for your in-depth summery of the problem on Aug 3, 2015! Lets hope your solution will be merged upstream soon.

Meanwhile I use this workaround:
sudo ln -s /usr/bin/mate-terminal /usr/bin/gnome-terminal

**Comment by monsta** [comment]
Ok, we have our own ```mate_desktop_prepend_terminal_to_vector``` function in libmate-desktop, and it's already used in panel's Run dialog. We can try using it in the code that handles custom app launcher as well.

**Comment by ganitau** [comment]
On Ubuntu mate I had the same problem so I looked in synaptic manager and xterm was not installed so I sudo apt-get install xterm and it worked for me..

**Comment by V-Kh** [comment]
I have the same problem with Fedora 25 (Mate). The only way is to run apps from the mate terminal directly.

**Comment by caesarivs** [comment]
This is present in Ubuntu MATE 16.04 as well:
setting TERM=mate-terminal does not work

**Comment by oliver-joos** [comment]
Until this issue is fixed you can use the workaround I wrote a year ago (see above):

`sudo ln -s /usr/bin/mate-terminal /usr/bin/gnome-terminal`

**Comment by AndriusWild** [comment]
The issue still exists on Mint MATE 18.2. Installing xterm and running "sudo ln -s mate-terminal xterm" helped (the script being open in xterm though). I also had to delete quotes in the Exec path in order  to make the script run Exec=/path/to/script.sh %F

**Comment by monsta** [comment]
Wow.
https://gitlab.gnome.org/GNOME/glib/merge_requests/795

**Comment by raveit65** [comment]
Does the issue still exits nowadays?
Glib MR is merged, so closing this.
