### ISSUE TITLE
Calendar: Edit button appears when Location is collapsed

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-panel#570]
Tested: Solus Mate 2017.04.18 fully updated

1) Open calendar applet in the panel tray
2) Edit button is visible
3) Expand Locations and button still present
4) Collapse Locations
5) Edit button gone

**Comment by philipzae** [comment]
![calendar edit button](https://cloud.githubusercontent.com/assets/4412114/25595740/fce40e9a-2ed6-11e7-8f7a-e85a5beb5dca.png)

**Comment by lukefromdc** [comment]
I've seen this for years when the calendar window is first popped up, never knew this was not intended behavior. Expanding and then collapsing the locations window (mine has no locations set) does cause it to disappear though, so perhaps it was never meant to show when the locations map is not showing. It opens clock preferences in the location tab, so that makes sense given that the clock preferences is also available from right-clicking the clock button

**Comment by WPo** [comment]
I confirm this behaviour for the calendar placed in an auto-hide left panel of mate panel V1.18.1 – but only, if the places are hidden at appearing time! If they are expanded (by default in my systems), this side effect doesn’t arise. And, of course, my places are populated with some cities.

Greetings – WPo

**Comment by philipzae** [comment]
Never seen this behaviour on any linux mint mate (13,17,18) or ubuntu mate (16.04) installation i've used in the last 4+ years.

**Comment by raveit65** [comment]
So, how should it look?
The edit button is only visible if the expander is expand, in any case ?

**Comment by lukefromdc** [comment]
When the calandar is popped up but not expanded(locations/world map not showing), the "edit" button on the right also should not be showing. With nothing in the "locations" list (my default), and the calendar by default not opening expanded, the "edit" button has always appeared, never knew it was not supposed to until this issue. Once the calendar has been expanded, on hiding locations the "edit" button is also hidden.
