### ISSUE TITLE
Updated Build instructions

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-panel#613]
Since I have to test #612 on bare-metal, because I wasn't able to reproduce #604 in a VM, I'd like updated build requirements / build order for the MATE stack up to mate-panel so I can minimize risk of screwing up my installation.

**Comment by raveit65** [comment]
No risk no fun :-)

**Comment by monsta** [comment]
One method to do it is to patch and rebuild .deb packages locally. See these articles for the instructions:
- [Howto to rebuild Debian packages](https://raphaelhertzog.com/2010/12/15/howto-to-rebuild-debian-packages/)
- [How to prepare patches for Debian packages](https://raphaelhertzog.com/2011/07/04/how-to-prepare-patches-for-debian-packages/)

You'll need a patch for that. Github allows an easy method to make a patch out of a commit: just append `.patch` to the commit URL (https://github.com/mate-desktop/mate-panel/commit/df36dcac197e8287ef5626d71556173b942c3f58 in this case). You'll get a plain text file which you can download and then import it as it's described in the second article.

**Comment by monsta** [comment]
Another method, which I use, is to build .deb packages from the source from git (this repo) combined with the corresponding `debian/` folder from [debian-packages repo](https://github.com/mate-desktop/debian-packages). Also you can use the source tarballs instead of git repo.
I suggest reading the articles first anyway, since they cover some essential topics. After that I can answer any remaining questions... 🙂 

In any case, it will be enough to rebuild only mate-panel.

**Comment by epgfm** [comment]
@monsta if you don't mind, I'd like to re-do the build/deploy in a VM, take note of the exact steps for 17.04 and add them somewhere (maybe in the HACKING file) preferably after you confirm I haven't done anything too wrong?

**Comment by epgfm** [comment]
## Building a .deb package for mate-panel from master in Ubuntu 17.04
### Note: the goal here is only to build .deb and deploy for testing, debian version control is most likely completely wrong but that's not the point.

Step 1 : Enable "Source Code" from the Software & Updates settings. Then run `sudo apt update && sudo apt full-upgrade`

Step 2 : `sudo apt install git dh-make dpkg-dev devscripts`

Step 3 :  Install mate-panel build dependencies: `sudo apt-get build-dep mate-panel`

Step 4 : Create temp directory for building and move into it: `mkdir BUILDDIR && cd BUILDDIR`

Step 5 : Recover source from github. We want both mate-panel repo and the debian package repo . Then we copy the debian/ folder from the debian package repo into the mate-panel directory. 
```bash
git clone https://github.com/mate-desktop/debian-packages
git clone https://github.com/mate-desktop/mate-panel
mv mate-panel mate-panel-1.18.3 # The name of the dir needs to correspond to the version of debian package
cp -rv debian-packages/mate-panel/debian mate-panel-1.18.3/debian # Copy debian package in the mix
tar czvf mate-panel_1.18.3.orig.tar.gz mate-panel-1.18.3/ # To make debuild happy this archive needs to exist
cd mate-panel-1.18.3/ 
dch --local myself # Email needs to be valid or debuild will complain
debuild -us -uc # Fingers crossed
```

Step 6 : install newly build packages
```bash
cd ..
sudo dpkg -i *.deb
```

**Comment by monsta** [comment]
Hmm that sounds like a mix of two methods... 🙂 
You need to enable source code repositories if you want to patch & build the source package provided in Ubuntu repos. But in this case, you don't need to clone our upstream source repo and debian-packages repo. Instead you need to get the source package via `sudo apt-get source mate-panel`, and it will contain both the source code and the Debian build files.
In case you choose to use our upstream source, please note that you'd also need to switch to 1.18 branch or to some "v1.18.x" tag. Otherwise you'd be building from the master branch which has all the latest stuf and isn't guaranteed to be stable.  🙂

**Comment by monsta** [comment]
Hmm I forgot about this. Should we close it?
