### ISSUE TITLE
Panel is without shadow

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/mate-panel#617]
#### Expected behaviour
Panel should have shadow such as windows.

#### Actual behaviour
MATE panel have not any shadow. 

Composition is enabled in Marco settings.
Even when I try to restart marco (by `marco --replace`) or mate-panel (by `killall mate-panel`), shadow is not visible.
I can have shadow in panel only by using external compositor such as compton with proper configuration.

#### Package version
marco 1.18.1
mate-panel 1.18.3

#### Linux Distribution
Arch Linux

**Comment by otwesou** [comment]
for what it's worth, the panel has had a shadow at various points in the past (back in the Gnome days, I believe) ... it would be there during one version, gone the next, back again, and it seems to have been gone for years now. i'd love to see it return on a permanent basis :-)

**Comment by elcste** [comment]
I like having the panel blend into my desktop, so I prefer the current lack of shadow. Maybe it can be made an option, in the great MATE tradition?

**Comment by TomaszGasior** [comment]
I agree. Option should be created for it. And this option should work **always* regardless of used compositor or window manager and regardless of components staring order (WM was started before panel or after).

**Comment by marcxjo** [comment]
I can confirm that the panel has a shadow when running Compton. For whatever it matters, Fedora 27, x86-64 architecture, panel v1.19.4.

Could this possibly be a Marco issue?

**Comment by lukefromdc** [comment]
I agree, it must be possible to disable panel shadows, and the issue with transparent panels would have to be fixed

**Comment by AnwarShah** [comment]
Any development on this issue. Shadowless panel is ugliest

**Comment by lukefromdc** [comment]
Shadows are not even possible without either compositing or pseudo-compositing, the latter is used in mate-panel when a user set background is selected and a compositor is not present. The code for that is very complex and to add shadows it would be necessary to enlarge the area copied from the desktop image to accomodate the dimensions of the shadow.   This would require modifying code that has been a source of bugs before when GTK versions changed-and it would also make the panel more resource intensive when running the system(default) background. It would be a major job and we are a small team.

With compositing, a shadow requires that a window take up an area beyond its decoration(if decorated) or contents(if undecorated like a menu or panel). The shadow is rendered on the window in this extra window area beyond the contents or decoration, it is not rendered on the contents of the window beneath.

You will notice that windows in general that have shadows in a compositing window manager do not have them when compositing is not used. This is because withouty compositing or pseudo-compositing(copying in the background beneath) it is not possible to have transparency, and without transparency the shadow would be over a black background RGB 0,0,0 rather than a transparent RGBA 0,0,0,0 background.

BTW, if shadows were forced with themes unable to override,  any theme setting a rounded corner on the panel would get an ugly square tip added to if if a shadow was forced and could not be overrridden by the user.

**Comment by TomaszGasior** [comment]
In my opinion:
- shadow should be rendered server-side, by window manager/compositor,
- user should have ability to disable it in GSettings (this setting may be invisible in GUI),
- panel shadow should be shown only when compositor is present,
- Hey, it's 2018! Pseudo-transprarency can be safely removed from mate-panel's codebase. Just don't use shadow when compositor is not present.

**Comment by lukefromdc** [comment]
You could probably get compiz or compiz-reloaded to do it now with the right settings in ccsm

**Comment by AnwarShah** [comment]
I installed and use compiz. I also use ccsm. There's no option to enable shadow for menu! I will continue using compiz if I can get the shadow.

**Comment by lukefromdc** [comment]
I can't talk you through it, but there is a "shadow window" entry in the options for the "decoration" plugin. Selecting "all" does not put a shadow on my panel, so you might try using the GUI to explicitly include the panel. Try an online search for details

**Comment by AnwarShah** [comment]
I tried manually selecting the panel. Still there is no shadow

**Comment by raveit65** [comment]
With that commit https://github.com/mate-desktop/mate-panel/commit/c4aedbddc01da6c0bf439e4229d77ae4c137df45
An example css for Menta and other light themes which can be used in
~.config/gtk-3.0/gtk.css
```
.mate-panel-menu-bar.horizontal.top > grid {
    border-style: outset;
    border-width: 0px 0px 1px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.horizontal.bottom > grid {
    border-style: outset;
    border-width: 1px 0px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.left > grid {
    border-style: outset;
    border-width: 0px 1px 0px 0px;
    border-color: rgba(0, 0, 0, 0.23);
}

.mate-panel-menu-bar.vertical.right > grid {
    border-style: outset;
    border-width: 0px 0px 0px 1px;
    border-color: rgba(0, 0, 0, 0.23);
}
```
