### ISSUE TITLE
disapeared keyboard icon pushes other icons on the panel

### ISSUE THREAD

**Issue by shalnoff** [mate-desktop/mate-panel#631]
#### Expected behaviour
the icon must appear and take its proper place

#### Actual behaviour
the icon does not appear, instead an empty place.
![mate_panel_keyboard_icon](https://user-images.githubusercontent.com/6167019/28752443-c6725990-751f-11e7-90b6-fab7f41c8f0d.png)

After several restarts of Mate (Ctrl-Alt-BkpSpace) the  icon appears and everything gets into place

#### Steps to reproduce the behaviour
problem occurs randomly, but quite often, after desktop loading

#### MATE general version
1.12.0

#### Linux Distribution
Distributor ID:	LinuxMint
Release:	17.3
Codename:	rosa

**Comment by alexarnaud** [comment]
Hello shalnoff,

I've experienced the same issue on Mate 1.8 but Mate 1.12 and 1.8 are 
deprecated. A work-around for this issue is to resize the panel or log 
out and re-login.

Could you reproduce this issue on more recent release ? (1.16 or 1.18)

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment]
See https://github.com/mate-desktop/mate-settings-daemon/issues/50
