### ISSUE TITLE
Panel Notification Randomness

### ISSUE THREAD

**Issue by caltrop2075** [mate-desktop/mate-panel#674]
#### Expected behaviour
NOT random!

#### Actual behaviour
notifications are random & problematic especially sound

notification -> sound
sometimes there is just a speaker
sometimes a speaker & microphone
again: the volume slider does NOT match the system settings in alsamixer
        alsamixer   mint-panel
master  100%        066%
alert     100%        000%
![mint panel issues](https://user-images.githubusercontent.com/31071746/31853816-3845c902-b65d-11e7-822b-bf9cb634cab2.png)

notification -> power
sometimes there is a battery with a cord
sometimes just the cord

#### Steps to reproduce the behaviour
it's RANDOM!
just using the system for any length of time

#### MATE general version
mate-panel 1.18.3
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Additional Information
 CPU: AMD Athlon(tm) II P360 Dual-Core x 2
 MEM: 3783MB (1009MB used)
SCSI: ATA WDC WD3200BEVT-7 320 GB
      TSSTcorp DVD+-RW TS-L633C
DISP: Resolution 1366x768 pixels
      OpenGL Renderer Gallium 0.4
      AMD RS880 (DRM 2.49.0 / 4.10.0-32-generic,LLVM 4.0.0)

**Comment by lukefromdc** [comment]
I assume you are referring to the icons in the tray and a problem with them either not coming up or the wrong icons being displayed, rather than to a popup notification issue. The latter would be mate-notification-daemon rather than mate-panel.

I have never had this happen on Debian Unstable with MATE built from git master, including when 1.18 was under development.  Neither tray icons nor popup notifications have ever displayed the randomness you describe.

Did you install Mint fresh, or update it to a new version? At least in the past, Mint didn't even support updating in place to a new version, although the underlying Ubuntu does.

**Comment by raveit65** [comment]
No answer from reporter since years.
