### ISSUE TITLE
DND between mate-panel and drawer throws Gtk-CRITICAL

### ISSUE THREAD

**Issue by info-cppsp** [mate-desktop/mate-panel#731]
just sg I see with `mate-panel --replace` on ub 18.04
when dragging to and from the drawer (like a terminal launcher), mp throws
```
(mate-panel:13093): Gtk-CRITICAL **: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```

very likely not in the drawer code, as for test I print out the fn name, when entering it, inside the drawer.c and I don't see that in the terminal, just the critical.

It seems that launchers are not widgets, but haven't checked this yet.

**Comment by muktupavels** [comment]
Run `mate-panel` from `gdb` and use `run --replace --g-fatal-warnings`.

**Comment by info-cppsp** [comment]
thanks. that helps, but before I get there, I have like a 100 other criticals.
But, you made me remember that I can connect to a process with gdb.
I'll check on this later, it is kinda unrelated to what I am doing right now.

**Comment by mintyDave7s** [comment]
This seems to be (potentially) a wider issue with mate-panel.  I now have to restart it many times per day because the panel disappears from my monitor.  It remains possible to click on it, though - the popups for the various icons, launchers, and notifiers remain active.  When I launch mate-panel from a terminal command line prompt, I am also seeing the widget_destroy error:

(mate-panel:9922): Gtk-CRITICAL **: 12:11:37.347: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

This is from a laptop running Linux Mint 19.3 Mate.

According to this (https://forums.gentoo.org/viewtopic-t-1060386-start-0.html) post, it seems to be a common programming error (unavoidable or not?) when using Gtk.

I may try to run from gdb to narrow down the culprit.

**Comment by lukefromdc** [comment]
Sounds like what was going on was `gtk_widget_destroy` being called more than once on the same widget. Once destroyed there is no longer a valid GTK widget to destroy, calling `gtk_widget_destroy`  again yields this warning.
