### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-panel#738]
#### Expected behaviour
Normal memory usage.

#### Actual behaviour
After starting the mate-session, mate-panel used 170 MB memory.
Then I started libreoffice writer, geeqie and mate-terminal from a panel launcher, and after few minutes, the memory usage of the panel is ~ 340 MB.
I started mate-terminal from panel launcher, and I started a build in the terminal. The memory usage now 393 MB.
This is normal?
All memory usage value reported by mate system monitor.
After restarting the panel the memory usage is ~60 MB.

#### Steps to reproduce the behaviour
Good question. This happens for me on every session start.

#### MATE general version
1.20

#### Package version
1.20.0 release

#### Linux Distribution
UHU-Linux UBK1

#### Link to downstream report of your Distribution
None.

**Comment by lukefromdc** [comment]
No it is not. Mine is sitting at 42 MB after many hours of running, with one panel and almost all space taken by many applets plus lots of open windows showing in the window-list

**Comment by flexiondotorg** [comment]
@rezso Can you edit your opening post and include the information we requested in the issue template. You've neglected to provide the information that would be useful to us.

**Comment by rezso** [comment]
@flexiondotorg: updated.

**Comment by info-cppsp** [comment]
can you check the memory usage with only one panel, with nothing on it please?
(also, do you have an up-to-date system? just making sure.)

**Comment by rezso** [comment]
Sorry for the late reply.
After more testing, it seems to me, that the hp-systray applet causes the high memory usage.
Weird, but true: this happens only with mate 1.20. (hplip systray applet works without high memory usage in Cinnamon, Classic Gnome, LXQt and MATE 1.18.)

**Comment by lukefromdc** [comment]
Question: is the hp systray applet an indicator (sni mode) or a traditional tray applet?

**Comment by DrReD** [comment]
**It is probably a different problem, but I just opened this issue downstream:**
[Fedora BUG: 1575091](https://bugzilla.redhat.com/show_bug.cgi?id=1575091)

Basically mate panel will eat memory up to 4,9GB on my machine.

**Comment by lukefromdc** [comment]
Can you turn the hp-systray applet off?

**Comment by Max-E** [comment]
I can also observe what looks like a memory leak in mate-panel (version 1.20.3 in Debian Buster.) I saw it get up to about a gigabyte at one point. Killing mate-panel and letting it get restarted resets memory usage down to 20-40 MiB. Currently sitting at 424.1 MiB after a few days.

**Comment by lukefromdc** [comment]
The Fedora bug refers to the Audacious tray icon causing a big memory leak. I use the Audacious tray icon all the time, with all applets built in-process on Debian Unstable and never see this. The same bug report also refers to a massive runup of RAM use in just a few hours, which I have never once seen from mate-panel no matter what I've done. 

As for WINE, I don't have that installed, most of the time it reportedly works poorly if at all on Debian Unstable (due to the constant changes everywhere else), and at any rate don't want to expose my encrypted box to potential Windows malware.  If I run into something requiring WINE it gets done with a one-shot install to a running Ubuntu live USB stick system.

At this point, I am wondering if some difference between Fedora and Debian with panels built with all applets in process in both cases is making a difference. I could probably fix this if I could duplicate it, but I cannot, and I don't have the bandwidth to download a whole Federa install and a MATE build environment within it(no landline).

**Comment by raveit65** [comment]
It seems fixed woth mate-panel-1.20.3
