### ISSUE TITLE
Widgets on vertical panel don't stick to their position after restarting the panel

### ISSUE THREAD

**Issue by o-alquimista** [mate-desktop/mate-panel#745]
During my sessions, all widgets are locked to a position, and they remain properly positioned during the current session. However, restarting the panel (or rebooting the system) will cause it to forget the position of my widgets, only when a vertical panel is used. The screenshots show how it looks _before and after._
![before](https://user-images.githubusercontent.com/25424263/36642177-5bedcf8c-1a1a-11e8-957a-fd884b55eb49.png)
![after](https://user-images.githubusercontent.com/25424263/36642181-62dba666-1a1a-11e8-8e40-535913ef470c.png)

### Additional info
- I have never tried this with an older version.
- I did not succeed in getting the stack trace for mate-panel. GDB says "No stack" when running "gdb mate-panel" followed by "backtrace".

#### MATE general version
1.20.0

#### Package version
community/mate-panel 1.20.0-1 (mate)

#### Linux Distribution
Arch Linux

#### Link to downstream report of your Distribution
https://bugs.archlinux.org/task/57631?project=5&opened=27326

**Comment by info-cppsp** [comment]
doesn't seem to be a problem with 1.18.6
I have noticed app launcher moving when I enable / disable the hide buttons on left panel with 1.20.
now app launchers move when enable / disable the hide buttons, but after `mate-panel --replace` they are where they are supposed to be.

I would say try using `mate-panel --replace` and add launchers one after another to a new panel.
maybe one launcher causes this, not the panel

**Comment by o-alquimista** [comment]
I experimented with mate-panel --replace and was able to reproduce the problem only when any of the widgets were placed to the very extremity of the panel. If I position all widgets so they don't touch the ends of the panel, after running --replace they remain in their positions.
![captura de tela em 2018-02-25 12-29-49](https://user-images.githubusercontent.com/25424263/36643293-2740bffc-1a28-11e8-8c8e-6512a1e52717.png)

**Comment by info-cppsp** [comment]
on ub 18.04 I can see that at the bottom of the left panel (near the bottom left corner of the screen)
the position looked up in dconf-editor changed from panel-right-stick off and a position around 900 (I have a fullhd monitor) to panel-right-stick on and position 37. on the panel object I have placed on the panel.

for me this means that for vertical panels the calculation of the panel widget is not fully correct...
not a problem with 1.18.6
tested with left panel size 40

**Comment by info-cppsp** [comment]
ok, so if you drag and drop a launcher, it won't get panel-right-stick on and it will stay at the end as it should.

**Comment by moqmar** [comment]
I still have the same problem - `panel-right-stick` is on for the widgets that should be at the bottom, but they are just below the last widget without `panel-right-stick`. Seems like the height of the panel is not fully taken into account here.

**Comment by uqs** [comment]
This is a recent regression. It used to work just fine that a "left" or "right" panel would honor the panel-right-stick and put the icons on the far side of the panel (the bottom, in that case).

This worked fine for me till 1 or 2 weeks ago. I'm now on 1.20.1-3 and I think I was at 1.18 before. So while a "top" or "bottom" panel honors the right-stick just fine, the "left" and "right" panels no longer do that in 1.20.1

Why even use right-stick you might ask? Well, I can't use an absolute pixel value like 1000 or something, because  a) I use the profile on different machines with different screen resolutions and b) on my laptop I use external displays (with different resolutions) every once in a while.

To everyone that has the problem: switch your panel to "top", does it look right? If so please report back (and switch back to "left" or "right").

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/mate-panel/pull/1004 should fix it...

**Comment by monsta** [comment]
Done. Fix is also picked to 1.22 and 1.20 branches.
