### ISSUE TITLE
clock applet window use always backdrop state

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#749]
#### Expected behaviour
Clock applet window should be able to switch between focus and backdrop state.

#### Actual behaviour
Clock applet window use always backdrop state

#### Steps to reproduce the behaviour
Install mate-themes from menta-backdrop branch and use Menta themes.
https://github.com/mate-desktop/mate-themes/tree/menta-backdrop

Open clock applet window and you will see the backdrop gtk-theme design.
Verify it with gtk3-inspector.
![clock-applet](https://user-images.githubusercontent.com/961604/36948443-1fc838aa-1fdb-11e8-9a87-15e8e55357ff.png)
As you can see status of MatePanelPopupWindow is always *backdrop*.

#### MATE general version
1.20
#### Package version
1.20
#### Linux Distribution
Noticed in fedora

#### Link to downstream report of your Distribution
N/A

**Comment by raveit65** [comment]
I forgot to say, this is really a showstopper for using new design for backdrop state with Menta themes or any other which support a backdrop design.

**Comment by muktupavels** [comment]
See my comment in https://github.com/mate-desktop/marco/issues/383...

**Comment by raveit65** [comment]
You mean the link to xfce in https://github.com/mate-desktop/marco/issues/383#issuecomment-367675331
?

**Comment by muktupavels** [comment]
Yes. The idea is that for all windows that are docks or splash-screens we tell gtk that these windows should appear as if they would been focused (to not add backdrop state).

And clock window has dock hint... So that should fix both panel and clock window. I have already pushed that change to metacity and compiz 0.9.x.

**Comment by raveit65** [comment]
Ok, your commit in metacity looks simple, but it depends on a lot of other commits.
Another reason to switch to metacity.
I will stop adding backdrop support to themes until this is done.....

**Comment by raveit65** [comment]
Hmm, menubar-applet use backdrop state too, wtf

**Comment by raveit65** [comment]
My theme workaround, a simulation of a normal/focused window state for this applets.
https://github.com/mate-desktop/mate-themes/commit/4c5599fe69252b33ab34419ff37696c65c0d3bd5

**Comment by lukefromdc** [comment]
One workaround for that would  be to ensure that anything with the .mate-panel-menu-bar style class and all child widgets thereof have the same theming.

In UbuntuStudio_Legacy the only thing I use :backdrop for is CSD window decorations, nothing else. That works and I have no problems with the panel with Marco or with my branch of compiz-reloaded which also leaves the :backdrop state on the same panel widgets

**Comment by muktupavels** [comment]
https://github.com/mate-desktop/marco/blob/master/src/core/window.c#L1325

You need to update that if...

**Comment by raveit65** [comment]
> In UbuntuStudio_Legacy the only thing I use :backdrop for is CSD window decorations, nothing else.

Good that your theme isn't affected, but a lot of themes use more than this setting, eg. the default gtk+ theme (adwaita).
Adwaita use also a backdrop setting for *labels*, in result the font-color of clock and menubar applet are affected.
So we need a general fix for this problem.

At least the backdrop settings for menta from this branch https://github.com/mate-desktop/mate-themes/tree/menta-backdrop are a huge visual change, and i am not sure if all, mostly conservative MATE users, will like this.
So, maybe it is possible to add a gsettings key for disable/enable backdrop state support ?

**Comment by lukefromdc** [comment]
Some kind of general fix is needed given that not all themes are mate-themes. A gsettings key is one way, but will break CSD application foreground/backdrop differences when disabled. Hardocding the offending  panel applets to read and apply the non :backdrop theming might be another way. Keep.

Starting point: how is this handled in gnome-panel with metacity?

**Comment by muktupavels** [comment]
If window manager supports `NET_WM_STATE_FOCUSED` then gtk will add `:backdrop` state to all windows that does not include this state...

Panels are not regular windows that get focus in / out events so this state is almost never set (it is possible to focus panel). There is no offending applets or anything like that, all widgets on such panel has `:backdrop` state and depending on theme applets might have backdrop styled things or not.

Since panels are not regular windows that are focused / unfocused it makes sense to tell gtk+ that they should look focused. Seems that it was first done in xfwm4, then I did same thing in `metacity` and also in `compiz`:
https://code.launchpad.net/~muktupavels/compiz/make-docks-appear-focused/+merge/339421

**Comment by lukefromdc** [comment]
Thus you are saying this is a Marco (and probably compiz-reloaded my branch) issue and not a mate-panel or theme issue at all.  We should fix it there if so.

**Comment by raveit65** [comment]
Issue is fixed.
