### ISSUE TITLE
VLC snap package missing panel icon

### ISSUE THREAD

**Issue by artgtan** [mate-desktop/mate-panel#811]
I'm using Ubuntu Mate 18.04, Mate 1.20.

Installing VLC from the Software Center works fine. The systray icon shows up as normal.

However, the snap version is missing the systray icon. I can share a screenshot if it helps. I don't know if it's a MATE panel issue or the snap package itself is missing the bundled icon.

**Comment by artgtan** [comment]
Changing org.mate.panel enable-sni-support to TRUE fixed the issue. Thank you.

**Comment by monsta** [comment]
> In fact, there is only one app that was broken: Telegram. Before upgrade, left-click on the icon popped up the app, another left-click closed the app (normal traditional behaviour). Now left-click don't work at all: happens nothing. Right-click shows Context Menu of the app (as normal).

Yes, this is how SNI works. It's like indicator applet, only with right click functioning instead of left click. See the discussions at https://github.com/mate-desktop/mate-panel/issues/547 and https://github.com/mate-desktop/mate-panel/pull/600.

**Comment by monsta** [comment]
@artgtan: did you upgrade from some previous Ubuntu version?

**Comment by artgtan** [comment]
@monsta No. I did a fresh install of Ubuntu Mate 18.04 with Mate 1.20.1 when I first encountered this issue.

**Comment by ssrublev** [comment]
> Yes, this is how SNI works. It's like indicator applet, only with right click functioning instead of left click. See the discussions at #547 and #600.

@monsta @raveit65 I am working now in latest Ubuntu-MATE. Now I see that I just cannot disable SNI in Ubuntu-MATE whenever "enable-sni-support" is "true" or "false". In Fedora-MATE I have not this problem, if "enable-sni-support" is "false", SNI is absent. Is there a way to disable finally this SNI in Ubuntu-MATE if setting "enable-sni-support" to false (and restarting mate-panel) doesn't work?

**Comment by lukefromdc** [comment]
I think Ubuntu-Mate still uses the separate indicator applet. Remove it from the panel and set "enable-sni-support" to false to disable SNI

**Comment by raveit65** [comment]
I think SNI-support is disabled as default in ubuntu.
```
rave@ubuntu:~$ gsettings reset org.mate.panel enable-sni-support
rave@ubuntu:~$ gsettings get org.mate.panel enable-sni-support
false
```
Done with that override.
```
rave@ubuntu:~$ cat /usr/share/glib-2.0/schemas/10_mate-common.gschema.override 
[org.gnome.desktop.wm.preferences:MATE]
button-layout='menu:minimize,maximize,close'
titlebar-uses-system-font=false

[org.gtk.Settings.FileChooser:MATE]
show-hidden=false
show-size-column=true
sort-directories-first=true
startup-mode='cwd'

[org.mate.caja.desktop]
computer-icon-visible=false
home-icon-visible=true
trash-icon-visible=false

[org.mate.disk-usage-analyzer.ui]
statusbar-visible=true

[org.mate.font-rendering]
antialiasing = 'rgba'
hinting = 'slight'

[org.mate.interface]
gtk-decoration-layout='menu:minimize,maximize,close'

[org.mate.Marco.general]
center-new-windows=false
compositing-manager=true
show-tab-border=false

[org.mate.NotificationDaemon]
theme='slider'

[org.mate.maximus]
no-maximize=true
undecorate=false

[org.mate.media-handling]
autorun-x-content-start-app=['x-content/software','x-content/video-bluray.xml','x-content/video-dvd.xml', 'x-content/video-hddvd.xml','x-content/video-svcd.xml','x-content/video-vcd.xml']

[org.mate.Marco.global-keybindings]
run-command-1='<Mod4>l'
run-command-2='<Shift>Print'
run-command-terminal='<Control><Alt>t'
switch-panels='disabled'
switch-windows='<Alt>Tab'
switch-windows-backward='<Alt><Shift>Tab'

[org.mate.Marco.keybinding-commands]
command-1='mate-screensaver-command --lock'
command-2='mate-screenshot --area --interactive'

[org.mate.Marco.window-keybindings]
move-to-center='<Control><Alt>KP_Begin'
move-to-corner-ne='<Control><Alt>KP_Page_Up'
move-to-corner-nw='<Control><Alt>KP_Home'
move-to-corner-se='<Control><Alt>KP_Page_Down'
move-to-corner-sw='<Control><Alt>KP_End'
move-to-side-n='<Control><Alt>KP_Up'
move-to-side-s='<Control><Alt>KP_Down'
move-to-side-e='<Control><Alt>KP_Right'
move-to-side-w='<Control><Alt>KP_Left'
tile-to-corner-ne='<Control><Mod4>KP_Page_Up'
tile-to-corner-nw='<Control><Mod4>KP_Home'
tile-to-corner-se='<Control><Mod4>KP_Page_Down'
tile-to-corner-sw='<Control><Mod4>KP_End'
tile-to-side-e='<Control><Mod4>KP_Right'
tile-to-side-w='<Control><Mod4>KP_Left'
toggle-shaded='<Control><Alt>s'

[org.mate.panel]
enable-sni-support=false
show-program-list=true

[org.mate.peripherals-mouse]
cursor-theme='mate'

[org.mate.peripherals-touchpad]
disable-while-typing=true
tap-to-click=true
three-finger-click=0
two-finger-click=0

[org.mate.pluma]
bracket-matching=true
display-line-numbers=true
display-right-margin=true
highlight-current-line=true
insert-spaces=true

[org.mate.screensaver]
lock-delay=1
mode='single'
themes=['screensavers-footlogo-floaters']

[org.mate.session]
idle-delay=30

[org.mate.SettingsDaemon.plugins.media-keys]
magnifier='<Alt><Mod4>m'
screenreader='<Alt><Mod4>s'
on-screen-keyboard='<Alt><Mod4>k'

[org.mate.sound]
event-sounds=true
input-feedback-sounds=true

[org.mate.system-monitor]
show-tree=true
solaris-mode=true

[org.mate.terminal.profile]
allow-bold=false
use-system-font=true
```

**Comment by monsta** [comment]
Yes, SNI is already disabled by default there. Apps that have libappindicator support are showing their icons in mate-indicator-applet via indicator-application.

What exactly is the problem, and with which apps?

**Comment by ssrublev** [comment]
My current problem apps are Telegram and Clementine (I use little apps at this install of Ubuntu-MATE). Also volume control is troubled.

+) As expected and was for years since Gnome2: 

Telegram and Clementine: single left click pops app window up, next single click pops it out (qbittorrent can do it even in Windows). Single right click brings context menu (often used to quit app). 

Volume control: single left click brings vertical volume indicator which can be regulated by mouse wheel while cursor staying there.

-) As it is wrongly now:

Telegram and Clementine: single left click don't popup app, it brings context menu (it's expected context menus should be always by right-click all the time). Single right click brings mate-panel context menu (traditionally I had to right-click border dots for that; the Help says the applet is called "Notification Area"). 

Volume control: single left click brings extended menu with horizontal volume indicator and Clementine controls but mouse wheel has no effect over volume control icon.

**Comment by raveit65** [comment]
Another different from fedora to ubuntu is that mate-panel is build with in-process (applets), because of better HIDPI support.
I reverted this for f28 because some user reported a memleak with notification-applet (reports are at github).
`switch back to build applets out of process`
https://src.fedoraproject.org/cgit/rpms/mate-panel.git/commit/?h=f28&id=73122688f47e179c996851a8e326a51de860dde0
Maybe another fallout with building the panel with `--with-in-process-applets=all` ?

**Comment by lukefromdc** [comment]
I build with --with-in-process-applets=all but don't run either of these applications or any snaps. I do not even have snapd installed.  

In terms of icons that don't show up at all, there have been icon problems before, often with applications that support indicator mode but name their icons in a way that does not actually meet the requirements for indicators. A lot of fallback code has been added to SNI mode in the tray to catch some of these cases.   In the case of a snap, isn't the icon provided inside the snap package itself, and thus is not present on the system? This implies we may need to add code to find snap icons by path, but I don't know enough about snaps to know if that path would be consistantly findable from the main system. 

I do remember issues GNOME had with the rival flatpack system, where in the early days they were unable to get flatpack packages to even use installed system GTK themes. Wonder if this is a problem with snaps themselves in a similar manner.

One more point about indicators/SNI: the only thing clicking on an indicator icon CAN do is open a menu. Whenever the desired behavior is to open the app (as with Avidemux), you get a one item context menu whose menuitem when clicked opens the app.  This has nothing to do with in or out of process, it is specific to the indicator specification.

**Comment by ssrublev** [comment]
I only wish I could "break" something that led to that disrupt I had today when Bluetooth appeared and all worked fine until reboot (or like in Fedora). It looked like something simple.

**Comment by monsta** [comment]
> Telegram and Clementine: single left click don't popup app, it brings context menu (it's expected context menus should be always by right-click all the time). Single right click brings mate-panel context menu (traditionally I had to right-click border dots for that; the Help says the applet is called "Notification Area").

Can you check what it says in the right-click menu -> About menu item?
Because you're describing the behavior of mate-indicator-applet with indicator-application showing app icons.

> Volume control: single left click brings extended menu with horizontal volume indicator and Clementine controls but mouse wheel has no effect over volume control icon.

Again, this is mate-indicator-applet with indicator-sound showing volume controls and audio player controls. It's not our volume control. You can run `mate-volume-control-applet` to get our volume control back.

Mouse wheel works on indicator-sound when the menu isn't shown. I forgot if it's a bug or intended behavior.

**Comment by ssrublev** [comment]
Thank you for the assistance! Right now, I have no access to that PC (it is Ubuntu-MATE installed from Ubuntu-MATE ISO and later upgraded online). I will get to that PC later in the week and will surely reply! If we can fix it, I would be very happy!

**Comment by ssrublev** [comment]
> Can you check what it says in the right-click menu -> About menu item?
Because you're describing the behavior of mate-indicator-applet with indicator-application showing app icons.

It says "Indicator Applet Complete" 1.20.0. 

In "Add to panel" menu I see "Indicator Applet", "Indicator Applet Appmenu" and "Indicator Applet Complete". When I add "Indicator Applet Application Menu" to panel, it says there "No Incicators" (despite apps are running). When I add other 2 items, I get this menu with "wrong behaviour". "Wrong behaviour" occured after upgrade to Ubuntu 18.04 — before upgrade all was OK. And Clementine icon was not big (now it's too big).

> You can run mate-volume-control-applet to get our volume control back.

That worked, thank you! Sounds good... "mate-volume-control-applet" is added to "Notification Area" 1.20.1 next to keyboard indicator. If "Notification Area" is not added to panel, this applet isn't shown.

**Comment by monsta** [comment]
I think there's no build of mate-indicator-applet (and indicators themselves) for Fedora.

**Comment by raveit65** [comment]
yes, indicators are ubuntu technologies, nobody had a reason to build them for fedora.
Why?
no unitity in fedora.

**Comment by monsta** [comment]
Unity is even discontinued by Canonical... though now there's a project to make indicators available on other distros, without dependencies on Unity stuff.

https://ayatanaindicators.github.io/about/
https://github.com/AyatanaIndicators

**Comment by raveit65** [comment]
Feel free to become a fedora packager to build them. I can sponsor you :)
Otherwise i don't see no one who has an interest.

**Comment by monsta** [comment]
Oh no, not me :smile: 
I just shared the info.

**Comment by ssrublev** [comment]
I'm still suffering from this. It is very sad for me and people who agreed with me.

Today Martin Wimpress marked it an "opinion" not a bug https://bugs.launchpad.net/ubuntu/+source/mate-indicator-applet/+bug/1769856

I disagree. If this worked well for ~15 years since Gnome2 and only now was broken, it's not just an opinion. Thank you thank you thank you Fedora-MATE for keeping this normal.

**Comment by ssrublev** [comment]
This SNI also spoils KDE. I was trying to fix annoying KDE "systray" flaws in both Ubuntu and Fedora and found here https://forum.manjaro.org/t/fixing-missing-tray-icons-in-plasma-5-10/26054 that I have to uninstall "sni-qt" package. And it helped.

Thank you once again @raveit65 so much for keeping Fedora-MATE free of these problems also in F29. I am so happy I have this option.

In Ubuntu-MATE, they just don't get anything on this, as I see. I can't understand why, and they are not trying to understand me. While Clementine in Ubuntu-MATE just can't be accessed via systray if it's minimized. It just disappears from taskbar and systray contain no menu item to call it back. They say it is Clementine problem. This is impossible because elsewhere it works OK and in Ubuntu-MATE it also worked OK previously (before this SNI woes appeared). They are silent here: https://ubuntu-mate.community/t/i-cannot-disable-sni-in-mate-panel-by-setting-enable-sni-support-to-false/17187/5

**Comment by lukefromdc** [comment]
What the heck is going on at Ubuntu that a gsettings change doesn't work? With vanilla mate-panel from git master I never have trouble turning SNI on or off to test something

**Comment by monsta** [comment]
It does work... It's just that indicators add some complexity to the situation.

**Comment by lukefromdc** [comment]
I have out native mate-panel SNI support. Maybe in Ubuntu the issue is that mate-panel's own gsettings key to enable to disable SNI support applies to the panel and not to the separate indicator applet?

**Comment by monsta** [comment]
Yes, it only affects the panel's tray area. When indicator-application is running, it shows the status icon of every app that has libappindicator support. These apps won't show their status icons in the tray area at the same time. So, toggling SNI setting of mate-panel won't affect them.

**Comment by ssrublev** [comment]
Thank you once again raveit65 so much for keeping Fedora-MATE free of these problems also in F34! =))

Years pass, no luck with Ubuntu. Recently I was upgrading it. And _during upgrade_ problem was temporarily solved (again!). 

Ubuntu's upgrade process apparently disables something that makes the issue solved until reboot. This means there must be a way to do something manually. But what?.. I keep discussing it here https://ubuntu-mate.community/t/i-cannot-disable-sni-in-mate-panel-by-setting-enable-sni-support-to-false/17187/7

I am still so happy raveit65 keeps this bug out of Fedora, again many thanks
