### ISSUE TITLE
Panel objects get resorted if there is no space left

### ISSUE THREAD

**Issue by LeoUnglaub** [mate-desktop/mate-panel#84]
If you connect your laptop to a beamer with a quit low resolution you have the problem that some icons in the panel get rearanged/reordered. Even if they are locked on to the panel.

![Auswahl_012](https://f.cloud.github.com/assets/734684/253674/f480505c-8bdc-11e2-8604-adf12f1f96a5.jpg)

**Comment by mirkoperillo** [comment]
confirm this issue on ubuntu mate 14.04 (mate 1.8.1) with my 24'' external monitor

**Comment by V3n3RiX** [comment]
no fix for this yet? even in dev branch, we can backport it to older versions

**Comment by opnoack** [comment]
This is a really annoying bug. Is this going to be fixed anytime soon?

**Comment by janmisek** [comment]
+1

**Comment by harlock974** [comment]
Issue still occurs in Mint LMDE2 (mate-panel 1.8.1+dfsg1-3). I still use the same workaround described on 30 dec 2013.

**Comment by Skydive** [comment]
Still occurring. +1
Will this be fixed soon? The workaround does not work for me.

**Comment by clefebvre** [comment]
Similar bug in GNOME2 https://bugs.launchpad.net/ubuntu/+source/gnome-panel/+bug/44082

**Comment by clefebvre** [comment]
Patch reported to fix the issue in GNOME2 https://bug314235.bugzilla-attachments.gnome.org/attachment.cgi?id=51170

**Comment by clefebvre** [comment]
Upstream bug report https://bugzilla.gnome.org/show_bug.cgi?id=341441

**Comment by clefebvre** [comment]
code commit in GNOME2: https://github.com/GNOME/gnome-panel/commit/8871b8e00929df310936f0d6ba8b7b88044e2e4f

**Comment by clefebvre** [comment]
Sadly it looks like this is already in mate-panel...

**Comment by opnoack** [comment]
Is there any update so far? I'd really like to make MATE my main desktop but with this bug it's annoying to work with external displays.

**Comment by milankni** [comment]
It seems to be related to issue: align applets with relative position #62

**Comment by monsta** [comment]
Well, since there were no more comments since @clefebvre's commit, I guess it has been indeed fixed.

**Comment by opnoack** [comment]
In which version of MATE will it be included?

**Comment by monsta** [comment]
Already released in 1.12.

**Comment by cpalaiop** [comment]
About:The MATE Panel 1.12.1
I had the same problem even though I had the latest version of MATE Panel.

I ran the command "mate-panel --reset", rebooted and everything is ok.

**Comment by Yasen6275** [comment]
Looks that is working atm. After sorting them one for the greatest used resoluyion, it keeps the order in aany smaler one

**Comment by monsta** [comment]
It's fixed only for locked applets (those you can't move on the panel freely). If you still have the issue, check if all your applets are locked (via right-click menu).

**Comment by harlock974** [comment]
Three year later, this issue is still there with version 1.14.0-1 (Linux Mint LMDE2), even with locked applets.
At each update I run the usual fix, in root terminal :

mv /usr/bin/mate-panel /usr/bin/mate-panel-later
echo "sleep 30;mate-panel-later">/usr/bin/mate-panel
chmod 755 /usr/bin/mate-panel

**Comment by AXDOOMER** [comment]
When my resolution changes, the position of my applets changes and doesn't go back to normal when I put the original resolution. This bugs me because I have to replace them to the correct spot.

**Comment by gaelanlloyd** [comment]
Looks like this has been an issue for a while.  I'm still encountering it today with the latest version of mate-panel (1.18.1-1).

When I run MATE in a guest VM and make the guest window full-screen the panel icons remember their absolute position and don't move over to the screen's new right edge.  Items that are supposed to be on the right edge end up appearing in the middle.

XFCE's panel has a nice way of handling this and doesn't have the same issue, but I'm not sure how they make it work.  I also really like XFCE's panel editor as it lets you easily move panel items around in a separate window list (and I opened [this ticket](https://github.com/mate-desktop/mate-panel/issues/527) for that discussion).  Building this panel-editing functionality into mate-panel and fixing the sizing bug would be a great addition to MATE!

**Comment by harlock974** [comment]
Hello,
Today I updated the last version for Linux Mint LMDE : 1.18.1-2+betsy
The bug is still there. Is there a prize for the longuest unsolved bug ?  :-D

**Comment by Lesik** [comment]
Well, with mate-panel you are moving around the panel widgets to arbitrary positions. Yes, you may have moved the clock to the most-right position of the panel, but the computer doesn't understand that. For the computer, you just moved it away from the left panel edge for X pixels.

Xfce doesn't have this issue because they have a different way of positioning panel widgets: Everything is stacked to the left side of the panel, except if an expanding widget comes up, in which case the rest is stacked to the right side of the panel. If there's two expanding widgets, the panel divides the free space onto both of them evenly.

You may like or not like Xfce's way of positioning widgets in the panel, but fact is that their way really (maybe unintentionally) circumvents this type of bug in a smart way. One downside of Xfce's panel is for example that you [can not completely center a widget](https://www.reddit.com/r/xfce/comments/245615) in the panel, as the free space in the panel is distributed evenly to both expanders.

Anyway, I personally don't see how MATE would fix this bug (which isn't their fault as they inherited it from GNOME 2) except if they switched to an Xfce-like positioning of the widgets, which is a lot of work and is unlikely to happen. This annoying bug, mostly affecting laptop users that often connect to external monitors or projectors, is likely going to stay (as it has already stayed for many, many years).

**Comment by Lesik** [comment]
Today I tried GNOME Flashback in a VM, and noticed that gnome-panel in GNOME Flashback does not suffer from this bug. The way they did is that the panel is divided into three sections – left, center, and right. When positioning items, you can add them to either of the sections, but you can't just slap it _somewhere_ on the panel. So gnome-panel is kinda like Xfce, except they have non-removable separators that are set to always expand, and they don't distribute free space evenly, instead there is always a perfectly centered section, one left, and one right.

Note that I am not talking about GNOME Classic, which is GNOME Shell with some extensions. I'm talking about GNOME Flashback:

![screenshot_debianstretch-gnome_2017-06-24_15 51 47](https://user-images.githubusercontent.com/2021487/27509130-39a5a656-58f6-11e7-9a32-83879df9eb10.png)
