### ISSUE TITLE
Clock applet and notification area are too narrow on high resolution screen

### ISSUE THREAD

**Issue by t3nsor** [mate-desktop/mate-panel#912]
#### Actual behavior
The clock applet is too narrow and does not show the full date and time. The notification area is too narrow and can't fit multiple icons. See screenshot: https://imgur.com/a/gINaHrQ

#### Steps to reproduce the behaviour
Occurs on a fresh installation of MATE on Debian 10 (Buster)

#### MATE general version
1.20.3

#### Linux Distribution
Debian 10

**Comment by lukefromdc** [comment]
I see that mate-panel 1.20.3 in Debian was release on Mon, 20 Aug 2018 13:04:35 +0200 , which means it was built against GTK 3.22 but is now being run against GTK 3.24.3-1, as GTK 3.24 did not arrive in Debian Unstable (ahead of testing) until September, after this package was built.

Debian needs to rebuild mate-panel in Buster (and probably Sid as well) against current GTK 3.24, because of fixes for wrong-width GtkPlug/GtkSocket widgets with HiDPI displays that required workarounds in mate-panel for GTK 3.22 but had to be excluded from GTK 3.24 builds to prevent exactly this sort of problem. 

Please open a bug report for this with Debian, as they need to fix this with a rebuild

**Comment by t3nsor** [comment]
Thanks, it looks like it's already fixed in unstable.
