### ISSUE TITLE
Inconsistent icon sizes in tray, duplicated "Take a break" icons.

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#980]
#### Expected behaviour
All icons should have the same size, no duplicates.

#### Actual behaviour
As described in caption.

#### Steps to reproduce the behaviour
After logging into system, keyboard layout indicator was too small. Telegram icon didn't fit tray. no duplicate icons. After resizing panel from 28 to 30 pixels Keyboard layout indicator became bigger, Telegram icon fits panel, "Take a break" applet moved to upper border and became duplicated. I can show a couple of screenshots but I don't know how to put them here and one of them has terrible quality. 

#### MATE general version
1.20.1

#### Package version
1.20.1-3ubuntu1

#### Linux Distribution
Ubuntu 18.04.2

#### Link to downstream report of your Distribution
Did not find any.

**Comment by lukefromdc** [comment]
Some of these tray bugs (those concerning legacy tray icons rather than indicators) come from problems with GtkStatusIcon, which has been deprecated by GTK devs and gets little maintainance. More such problems come from issues with GtkPlug and GtkSocket, which have gotten a little help for HiDPI issues from GTK's devs but not a whole lot. 

GTK's developers seem to be focussed on wayland, so everything they have that is Xorg-only is deprecated. GtkStatusIcon, GtkPlug, and GtkSocket all depend on Xembed, and that's where a lot of nasty tray and out of process icon rendering bugs seem to be coming from these days.

Thus, some of these bugs may be impossible to fix without patching GTK itself and hoping GTK devs accept those patches upstream.

**Comment by blackpoint200** [comment]
Thank you for detailed answer. I fixed that by adding PPA and updating to 1.22 but then I've got 2 keyboard layout indicators (one from IBUS and the second one from MATE) and 2 watches (one applet showed only time and the second one time and date). After deleting one of applets for some reason audio volume icon disappeared. I had to switch back to Gnome because of those bugs.

**Comment by lukefromdc** [comment]
Maybe you deleted the indicator applet itself? That would of course take out both the keyboard and audio volume indicators in Ubuntu. Removing ibus will of course remove it's indicator

**Comment by blackpoint200** [comment]
I checked how MATE works in Fedora just to know if those bugs related to Ubuntu or to MATE and seems like now it works correctly. I found that ibus dependency in MATE seems to be Ubuntu specific. I can use just libmatekbd for keyboard layout. If I delete audio volume icon, only this applet disappears, other applet stay on their places. Thank you for trying to help me.

**Comment by raveit65** [comment]
User is gone from github. Closing.
